// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = WorkSectionSlice | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * First Name field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.first_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	first_name: prismic.KeyTextField;

	/**
	 * Last Name field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.last_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	last_name: prismic.KeyTextField;

	/**
	 * Profile Picture field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.profile_picture
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	profile_picture: prismic.ImageField<never>;

	/**
	 * Tag Line field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.tag_line
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	tag_line: prismic.KeyTextField;

	/**
	 * About Heading field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.about_heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	about_heading: prismic.KeyTextField;

	/**
	 * About Line field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.about_line
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	about_line: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

/**
 * Item in *Work → Default → Primary → Work Item*
 */
export interface WorkSectionSliceDefaultPrimaryWorkItemItem {
	/**
	 * Work Title field in *Work → Default → Primary → Work Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_section.default.primary.work_item[].work_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	work_title: prismic.KeyTextField;

	/**
	 * Work Description field in *Work → Default → Primary → Work Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_section.default.primary.work_item[].work_description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	work_description: prismic.KeyTextField;

	/**
	 * Work Dates field in *Work → Default → Primary → Work Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_section.default.primary.work_item[].work_dates
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	work_dates: prismic.KeyTextField;

	/**
	 * Work URL field in *Work → Default → Primary → Work Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_section.default.primary.work_item[].work_url
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	work_url: prismic.KeyTextField;

	/**
	 * Work Icon field in *Work → Default → Primary → Work Item*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_section.default.primary.work_item[].work_icon
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	work_icon: prismic.ImageField<never>;

	/**
	 * Work Icon Color field in *Work → Default → Primary → Work Item*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_section.default.primary.work_item[].work_icon_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	work_icon_color: prismic.ColorField;
}

/**
 * Primary content in *Work → Default → Primary*
 */
export interface WorkSectionSliceDefaultPrimary {
	/**
	 * Work Heading field in *Work → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_section.default.primary.work_heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	work_heading: prismic.KeyTextField;

	/**
	 * Work Item field in *Work → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_section.default.primary.work_item[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	work_item: prismic.GroupField<Simplify<WorkSectionSliceDefaultPrimaryWorkItemItem>>;
}

/**
 * Default variation for Work Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSectionSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<WorkSectionSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Work*
 */
type WorkSectionSliceVariation = WorkSectionSliceDefault;

/**
 * Work Shared Slice
 *
 * - **API ID**: `work_section`
 * - **Description**: WorkSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSectionSlice = prismic.SharedSlice<'work_section', WorkSectionSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			WorkSectionSlice,
			WorkSectionSliceDefaultPrimaryWorkItemItem,
			WorkSectionSliceDefaultPrimary,
			WorkSectionSliceVariation,
			WorkSectionSliceDefault
		};
	}
}
